(define-derived-mode gsql-mode shell-script-mode "GSQL"
  )

(font-lock-add-keywords
 'gsql-mode
 '(
   ("\\$\\([0-9]*\\)" . (1 font-lock-function-name-face nil t))
   (":\\(\\w+\\)" . (1 font-lock-variable-name-face nil t))
   ("\\(\\w+\\)\\." . (1 font-lock-variable-name-face nil t))
   ("\\(\\@+\\w+\\)" . (1 font-lock-variable-name-face nil t))
   ("QUERY" . font-lock-keyword-face)
   ("OrAccum" . font-lock-keyword-face)
   ("AvgAccum" . font-lock-keyword-face)
   ("SumAccum" . font-lock-keyword-face)
   ("POST-ACCUM" . font-lock-keyword-face)
   ("INSTALL" . font-lock-keyword-face)
   ("SELECT" . font-lock-keyword-face)
   ("WHERE" . font-lock-keyword-face)
   ("USE" . font-lock-keyword-face)
   ("USING" . font-lock-keyword-face)
   ("GRAPH" . font-lock-keyword-face)
   ("FOR" . font-lock-keyword-face)
   ("CREATE" . font-lock-keyword-face)
   ("LOADING" . font-lock-keyword-face)
   ("INTERPRET" . font-lock-keyword-face)
   ("JOB" . font-lock-keyword-face)
   ("RUN" . font-lock-keyword-face)
   ("LOAD" . font-lock-keyword-face)
   ("FROM" . font-lock-keyword-face)
   ("TO" . font-lock-keyword-face)
   ("VALUES" . font-lock-keyword-face)
   ("VERTEX" . font-lock-keyword-face)
   ("EDGE" . font-lock-keyword-face)
   ("UNDIRECTED" . font-lock-keyword-face)
   ("DIRECTED" . font-lock-keyword-face)
   ("PRIMARY_ID" . font-lock-keyword-face)
   ("DEFINE" . font-lock-keyword-face)
   ("FILENAME" . font-lock-keyword-face)
   ("PRINT" . font-lock-keyword-face)
   ("ACCUM" . font-lock-keyword-face)

   ("INT" . font-lock-type-face)
   ("STRING" . font-lock-type-face)
   ("TRUE" . font-lock-type-face)
   ("FALSE" . font-lock-type-face)
   ("DATETIME" . font-lock-type-face)
 ))
