(add-hook 'ess-mode-hook
	  '(lambda()
	     (local-set-key [?\M-\;] 'ess-mode-accel)
	     (local-set-key "\C-\M-x" 'ess-eval-paragraph)
	     (local-set-key "\C-x\C-e" 'ess-eval-line)
	     (local-set-key "_" 'self-insert-command)
	     ))
(defun ess-mode-accel ()
  "Insert R statemnts quickly by abbreviations."
  (interactive)
  (message "(s)hebang, (a)rguments, (l)edgend, a(x)is")
  (let ((c (read-char)))
    (cond
     ;; (s)hebang
     ((equal c ?s)
      (open-line 1) (insert "#!/home/hchiba/bin/rscript") (next-line 1)
      (insert-statement "USAGE =")
      (open-line 1) (insert "\"Usage: ") (next-line 1)      
      (insert-statement "-h: help")
      (insert-statement "\"")
      (insert-statement "### Get command line argumants ###")
      (insert-statement "getopts(\"h\")")
      (insert-statement "if (opt.h) {")
      (insert-statement "cat(USAGE)")
      (insert-statement "q()")
      (insert-statement "}")
      (insert-statement "##################################")
      (insert-statement "")
      )
     ;; (a)rguments
     ((equal c ?a)
      (insert-statement "if (is.na(ARGV[1]) || is.null(stdin)) {")
      (insert-statement "cat(USAGE)")
      (insert-statement "q()")
      (insert-statement "} else {")
      (insert-statement " = ARGV[1]")
      (insert-statement "}")
      (previous-line 2)(back-to-indentation)
      )     
     ;; (l)egend
     ((equal c ?l)
      (insert-statement "legend(, ,")
      (insert-statement "lwd=1, bg='white',")
      (insert-statement "legend=c('',''),")
      (insert-statement "lty=c(1,5))")
      )
     ;; a(x)is
     ((equal c ?x)
      (insert-statement "axis(1, at=, labels=)")
      (previous-line 1)(back-to-indentation)(forward-char 11)
      )
     )))